version: "3.9"

services:
  ganache:
    image: trufflesuite/ganache-cli
    command: --db ./chain/

  executor:
    build: ./Executor
    depends_on:
      - ganache
      - publisher
    ports:
      - 8080:8080
    environment:
      - GANACHE_URL=http://ganache:8545
      - PUBLISHER_URL=http://publisher:8081
  
  publisher:
    build: ./Publisher
