version: "3.9"

services:
  orderer:
    build: .
    # depends_on:
    #   - executor
    ports:
      - 8080:8080
    environment:
      - executer_url=http://executor:8080
  
#   executor:
#     build: ./Executor